targets:
 $default:
  sources:
    include:
      - lib/domain/**
      - lib/data/services/drift/**
      - lib/utils/data/services/json_converter.dart
    exclude:
      - lib/**.freezed.dart
      - lib/**.g.dart
  builders:
    drift_dev:
      options:
        databases:
          keeper_db: lib\data\services\drift\local_db.dart