targets:
 $default:
  sources:
    include:
      - lib/domain/**
      - lib/data/services/drift/**
      - lib/utils/data/services/json_converter.dart
    exclude:
      - lib/**.freezed.dart
      - lib/**.g.dart