services:
  db:
    image: postgres:alpine
    container_name: keeper_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 191130
      POSTGRES_DB: keeper
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local