// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'keeper_app.dart';

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/users',
        uri: Uri.parse('/users'),
        routeBuilder: b0Builder,
      ),
    ];

const routePaths = (
  path: '/',
  users: '/users',
);
